name: integration-testing
on:
  pull_request:
    branches: [develop, main]

jobs:
  Run-Integration-Tests:
    runs-on: ubuntu-latest
    env:
      SOLUTION_DIRECTORY: PharmacyInformationSystem
      PROJECT_DIRECTORY: Pharmacy
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: root
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dotnet ef
        run: dotnet tool install --global dotnet-ef

      - name: Install dependencies
        run: dotnet restore ${SOLUTION_DIRECTORY}

      - name: Create Migrations
        run:
          dotnet ef migrations add InitialCreate --project ${SOLUTION_DIRECTORY}\/${PROJECT_DIRECTORY};
      - name: Update Database
        run: dotnet ef database update --project ${SOLUTION_DIRECTORY}\/${PROJECT_DIRECTORY};
      - name: Test
        run: dotnet test ${SOLUTION_DIRECTORY} --no-restore --verbosity quiet --filter FullyQualifiedName\!~UnitTests
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_PASSWORD: root