name: Call Reusable CI

on:
  push:
    branches:
      - '*'

jobs:
  call-workflow:
    uses: vladimirr9/dummyrepo/.github/workflows/my-callable-workflow.yml@085d6e186375a55d3ec95c759d29efe854700ea6
