name: unit-testing
on:
  pull_request:
    branches: [develop, main]

jobs:
  Run-Unit-Tests:

    runs-on: ubuntu-latest
    env:
      SOLUTION_DIRECTORY: PharmacyInformationSystem
      PROJECT_DIRECTORY: Pharmacy
    strategy:
      matrix:
        dotnet-version: ['5.0.x']

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore ${SOLUTION_DIRECTORY}
      - name: Build
        run: dotnet build ${SOLUTION_DIRECTORY} --configuration Release --no-restore
      - name: Test
        run: dotnet test ${SOLUTION_DIRECTORY} --no-restore --verbosity quiet --filter FullyQualifiedName\!~IntegrationTests